name: Build Camillian Connect APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable
          cache: true

      - name: Fix Flutter project folders
        run: |
          mkdir -p lib
          mkdir -p assets

          if [ -f main.dart ]; then
            mv main.dart lib/main.dart
          fi

          if [ -f camillian_hero.png ]; then
            mv camillian_hero.png assets/camillian_hero.png
          fi

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: camillian-connect-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
